[project]
name = "dycco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "R J Ladyman", email = "it@file-away.co.uk" }
]
requires-python = ">=3.14"
dependencies = [
    "importlib-metadata==5.0.0",
    "markdown>=2.4",
    "pygments>=2.7.4",
    "pystache>0.5.3",
    "zipp==3.10.0",
]

[project.scripts]
dycco = "dycco:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["dycco*"]
